### ISSUE TITLE
App associating itself to wrong network in docker-compose

### ISSUE THREAD

**Issue by tipra28** [fredrikburmester/streamystats#11]
Hi!
I've just deployed the app in my homelab and love the interface. I'm just facing a certain issue where the app links itself to the wrong network in my docker-compose file.

```
services:
  sms_app:
    container_name: sms_app
    image: fredrikburmester/streamystats-nextjs:edge
    depends_on:
      - sms_phoenix
    networks:
      - proxy
      - backend
    environment:
      API_URL: "http://sms_phoenix:4000/api"
    labels:
      - traefik.enable=true
      - traefik.http.routers.sms.rule=Host(`sms.domain.com`)
      - traefik.http.routers.sms.entrypoints=https
      - traefik.http.services.sms.loadbalancer.server.port=3000
      - traefik.http.routers.sms.tls=true
      - traefik.http.routers.sms.tls.certresolver=cloudflare
  sms_phoenix:
    container_name: sms_phoenix
    image: fredrikburmester/streamystats-phoenix:edge
    environment:
      DATABASE_URL: "ecto://postgres:postgres@sms_db/streamystat"
      SECRET_KEY_BASE: "randomstringhere"
    depends_on:
      - sms_db
    networks:
      - backend
  sms_db:
    container_name: sms_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend
    volumes:
      - ./appdata/db:/var/lib/postgresql/data
    logging:
      driver: "none"
networks:
  proxy:
    external: true
  backend:
    external: true
```

As you can see in the above I have two networks deployed
1. Proxy for all the frontend apps which traefik also resides on (172.20.10.0/24)
2. Backend for all the support apps (databases, elastisearch etc) (172.21.0.0/24)

When I deploy the app the app links to 172.21.0.19:3000 on the backend network. Which obviously is not available to traefik and therefore it refuses to launch. 

I've deployed similar compose files where I've not faced this issue. I'm not sure if I need to add something in the docker compose file to control your apps network or is it something on the app side which needs to be sorted. 

An example of another service Linkwarden - https://pastebin.com/aywH0PQ3 - which I have no issues with
