### ISSUE TITLE
Error creating server

### ISSUE THREAD

**Issue by koelle25** [fredrikburmester/streamystats#22]
Hi, I was trying for quite some time now, but I don't get it to work.. Firing up the Streamystats compose stack no problem, but it won't let me add my Jellyfin server.

I've already made sure that reaching my Jellyfin and making API requests works, by executing the following command from both the frontend and the backend container (after installing `curl` there of course):
`curl -H "Authorization: MediaBrowser Token=<my_api_token>" https://jelly.mydomain.de/System/ActivityLog/Entries`

Log:
```
streamystats-backend   | 11:12:42.775 request_id=GDTwqKLPRioIEXEAAACh [info] GET /servers
streamystats-backend   | 11:12:42.776 request_id=GDTwqKLPRioIEXEAAACh [info] Sent 404 in 238µs
streamystats-backend   | 11:12:42.793 request_id=GDTwqKPYo1Gr7bIAAAFD [info] POST /servers
streamystats-backend   | 11:12:42.793 request_id=GDTwqKPYo1Gr7bIAAAFD [info] Sent 404 in 241µs
streamystats-frontend  | Error: Failed to create server
streamystats-frontend  |     at l (/app/.next/server/chunks/464.js:1:1753)
streamystats-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
streamystats-frontend  |     at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
streamystats-frontend  |     at async rE (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8148)
streamystats-frontend  |     at async r7 (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
streamystats-frontend  |     at async doRender (/app/node_modules/next/dist/server/base-server.js:1427:30)
streamystats-frontend  |     at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1588:28)
streamystats-frontend  |     at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1496:28)
streamystats-frontend  |     at async NextNodeServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1924:24)
streamystats-frontend  |     at async NextNodeServer.renderToResponseImpl (/app/node_modules/next/dist/server/base-server.js:1962:32) {
streamystats-frontend  |   digest: '1659854444'
streamystats-frontend  | }
```

Nothing in the Jellyfin logs.

Is there anything I can do to further debug this problem?

In case it's relevant:
- My Jellyfin is publicly exposed with HTTPS via Traefik and Let's Encrypt-Certificate
  - I also tried using the internal IP:Port with HTTP, but same error
<details>
<summary>docker-compose.yml</summary>

```
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jelly.mydomain.de`)
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.server.scheme=http
    #network_mode: 'host'
    networks:
      - traefik-public
    ports:
      # WebUI: Http webUI
      - 8096:8096
      # Https webUI (you need to set up your own certificate)
      - 8920:8920
      # Optional - Allows clients to discover Jellyfin on the local network
      - 7359:7359
      # Optional - Service discovery used by DNLA and clients
      - 1900:1900
    restart: 'unless-stopped'
    #user: 99:100
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/appdata/jellyfin/cache:/cache
      - /mnt/user/files/Videos/Serien:/tv:ro
      - /mnt/user/files/Videos/Filme:/movies:ro

  streamystats-frontend:
    image: fredrikburmester/streamystats-nextjs:edge
    container_name: streamystats-frontend
    depends_on:
      - streamystats-backend
    environment:
      - API_URL=http://streamystats-backend:4000
    networks:
      - streamystats
    ports:
      - 3003:3000
    restart: 'unless-stopped'

  streamystats-backend:
    image: fredrikburmester/streamystats-phoenix:edge
    container_name: streamystats-backend
    depends_on:
      - streamystats-db
    environment:
      - DATABASE_URL=ecto://${STREAMYSTATS_DB_USER:-postgres}:${STREAMYSTATS_DB_PASSWORD?Variable STREAMYSTATS_DB_PASSWORD not set}@streamystats-db/${STREAMYSTATS_DB_NAME:-${STREAMYSTATS_DB_USER:-postgres}}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE?Variable SECRET_KEY_BASE not set}
    networks:
      - streamystats
    #ports:
    #  - 4000:4000
    restart: 'unless-stopped'

  streamystats-db:
    image: postgres:16-alpine
    container_name: streamystats-db
    environment:
      - POSTGRES_USER=${STREAMYSTATS_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${STREAMYSTATS_DB_PASSWORD?Variable STREAMYSTATS_DB_PASSWORD not set}
      - POSTGRES_DB=${STREAMYSTATS_DB_NAME:-${POSTGRES_USER:-postgres}}
    networks:
      - streamystats
    restart: 'unless-stopped'
    volumes:
      - /mnt/user/appdata/jellyfin/streamystats-db:/var/lib/postgresql/data

networks:
  streamystats: {}
  traefik-public:
    external: true
```

</details>

**Comment by fredrikburmester** [comment]
I reviewed your compose file but didn't spot any issues. You might want to try updating and see if anything changes. Otherwise, try setting it up without modifying the compose file to determine if the problem is with your JF server or the setup itself.

**Comment by koelle25** [comment]
Thank you, I finally found the culprit. I forgot the `/api` in the `API_URL` environment variable...
Wrong: `API_URL=http://streamystats-backend:4000`
Correct: `API_URL=http://streamystats-backend:4000/api`

Unrelated to this problem, but there was also a wrong variable expansion line for the database service.
Wrong: `POSTGRES_DB=${STREAMYSTATS_DB_NAME:-${POSTGRES_USER:-postgres}}`
Correct: `POSTGRES_DB=${STREAMYSTATS_DB_NAME:-${STREAMYSTATS_DB_USER:-postgres}}`

For anyoine interested, this is now the functioning compose file:
<details>
<summary>docker-compose.yml</summary>

```
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jelly.mydomain.de`)
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.server.scheme=http
    #network_mode: 'host'
    networks:
      - traefik-public
    ports:
      # WebUI: Http webUI
      - 8096:8096
      # Https webUI (you need to set up your own certificate)
      - 8920:8920
      # Optional - Allows clients to discover Jellyfin on the local network
      - 7359:7359
      # Optional - Service discovery used by DNLA and clients
      - 1900:1900
    restart: 'unless-stopped'
    #user: 99:100
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/appdata/jellyfin/cache:/cache
      - /mnt/user/files/Videos/Serien:/tv:ro
      - /mnt/user/files/Videos/Filme:/movies:ro

  streamystats-frontend:
    image: fredrikburmester/streamystats-nextjs:edge
    container_name: streamystats-frontend
    depends_on:
      - streamystats-backend
    environment:
      - API_URL=http://streamystats-backend:4000/api
    networks:
      - streamystats
    ports:
      - 3003:3000
    restart: 'unless-stopped'

  streamystats-backend:
    image: fredrikburmester/streamystats-phoenix:edge
    container_name: streamystats-backend
    depends_on:
      - streamystats-db
    environment:
      - DATABASE_URL=ecto://${STREAMYSTATS_DB_USER:-postgres}:${STREAMYSTATS_DB_PASSWORD?Variable STREAMYSTATS_DB_PASSWORD not set}@streamystats-db/${STREAMYSTATS_DB_NAME:-${STREAMYSTATS_DB_USER:-postgres}}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE?Variable SECRET_KEY_BASE not set}
    networks:
      - streamystats
    #ports:
    #  - 4000:4000
    restart: 'unless-stopped'

  streamystats-db:
    image: postgres:16-alpine
    container_name: streamystats-db
    environment:
      - POSTGRES_USER=${STREAMYSTATS_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${STREAMYSTATS_DB_PASSWORD?Variable STREAMYSTATS_DB_PASSWORD not set}
      - POSTGRES_DB=${STREAMYSTATS_DB_NAME:-${STREAMYSTATS_DB_USER:-postgres}}
      #- PGDATA=/var/lib/postgresql/data
    networks:
      - streamystats
    restart: 'unless-stopped'
    volumes:
      - /mnt/user/appdata/jellyfin/streamystats-db:/var/lib/postgresql/data

networks:
  streamystats: {}
  traefik-public:
    external: true
```

</details>
<details>
<summary>.env</summary>

```
# Optional - alternative address used for autodiscovery
JELLYFIN_PublishedServerUrl=https://jelly.mydomain.de

PUID=99
PGID=100
UMASK=022

SECRET_KEY_BASE=aRandomStringGeneratedWithOpensslRand-hex64
STREAMYSTATS_DB_USER=streamy
STREAMYSTATS_DB_PASSWORD=MySuperSecurePassword
STREAMYSTATS_DB_NAME=streamystats
```
</details>
