### ISSUE TITLE
streamystats-phoenix-1  curl error

### ISSUE THREAD

**Issue by Nostradamus1973** [fredrikburmester/streamystats#3]
Good morning,,

I'm getting the following error with streamystats-phoenix-1

OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown

Here is my compose file:
```
services:
  app:
    image: fredrikburmester/streamystats-nextjs:latest
    ports:
      - "3011:3000"
    depends_on:
      - phoenix
    networks:
      - backend
    environment:
      API_URL: "http://phoenix:4000/api"

  phoenix:
    image: fredrikburmester/streamystats-phoenix:latest
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/streamystat"
      SECRET_KEY_BASE: "r0NgGxu5ETTDgF5G7mJsMevMbAF7y4w0IJlCRjzxHqSjbcrPqTQTzajOH0ne0sHH"
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend
    volumes:
      - /home/nostradamus/dockers/streamystats/pgdata/:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend:
```
I have it running on port 3011 to avoid a conflict.

Thank you and have a nice day,
