### ISSUE TITLE
Watch Time Per Hour wrong timezone

### ISSUE THREAD

**Issue by darkmyregaming** [fredrikburmester/streamystats#99]
Watch Time Per Hour on the dashboard seems to be using the wrong timezone, despite History and Activity Log showing correct times. It would be great if this could use the server timezone in some way to make this a useful data point.

**Comment by fredrikburmester** [comment]
Could you provide some examples?

**Comment by darkmyregaming** [comment]
Sorry, my timezone is Australia/Sydney (UTC+10). I cleared the database and tried a test playback, at approx 1620 local time. Activities table in the database shows the correct UTC time being logged:

> "id"	"jellyfin_id"	"name"	"short_overview"	"type"	"date"	"user_id"	"server_id"	"severity"	"inserted_at"	"updated_at"
> 959	64214	"darkmyre has finished playing .."		"VideoPlaybackStopped"	"2025-05-21 06:25:37"	2	1	"Information"	"2025-05-21 06:28:36"	"2025-05-21 06:28:36"
> 960	64213	"darkmyre has started playing .."		"VideoPlayback"	"2025-05-21 06:21:13"	2	1	"Information"	"2025-05-21 06:28:36"	"2025-05-21 06:28:36"

But watch time per hour shows this as 0800:

![Image](https://github.com/user-attachments/assets/0596e2c6-aaa7-48bc-8163-db70b87abaa0)

playback_sessions also shows correct timestamps:

> "id"	"play_duration"		"start_time"	"end_time"	"inserted_at"	"updated_at"	"last_activity_date"	"last_playback_check_in"	
> 1	190	"2025-05-21 06:21:14"	"2025-05-21 06:25:39"	"2025-05-21 06:25:39"	"2025-05-21 06:25:39"	"2025-05-21 06:25:21"	"2025-05-21 06:25:21"

**Comment by fredrikburmester** [comment]
@darkmyregaming could you try the pr and see if it solves your issue?

**Comment by ghost** [comment]
Sorry it's taken so long, I somehow missed the last two reply notifications from github.

I've updated to the docker tag and added NEXT_PUBLIC_TIMEZONE to my docker-compose and tried a couple of test watches - the chart is now being updated according to UTC, like its somehow not reading either of the environmental variables?

My docker-compose entry for the app is as follows in case that's relevant:

```
  streamystats:
    image: fredrikburmester/streamystats-nextjs:pr-117
    container_name: streamystats
    depends_on:
      - phoenix
    ports:
      - 3000:3000
    environment:
      API_URL: "http://phoenix:4000/api"
      TZ: "Australia/Sydney"
      NEXT_PUBLIC_TIMEZONE: "Australia/Sydney"
    restart: unless-stopped
```
